Update vless.yml

diff --git a/.github/workflows/vless.yml b/.github/workflows/vless.yml
--- a/.github/workflows/vless.yml
+++ b/.github/workflows/vless.yml
@@ -46,10 +46,10 @@ jobs:
           echo "Updating DOMAIN_NAME to ${DOMAIN_NAME}"
           sed -i "s/%domain_name%/${DOMAIN_NAME}/g" ./vless/wrangler.toml
 
-      # Step 5: Check if index.js exists in vless folder
-      - name: Check if index.js exists
+      # Step 5: Check if _worker.js exists in vless folder
+      - name: Check if _worker.js exists
         run: |
-          ls -l ./vless/index.js || echo "index.js not found in ./vless"
+          ls -l ./vless/_worker.js || echo "_worker.js not found in ./vless"
 
       # Step 6: Install dependencies locally
       - name: Install dependencies locally
@@ -59,7 +59,7 @@ jobs:
       # Step 7: Obfuscate the Worker code
       - name: 🔒 Obfuscate code
         run: |
-          npx javascript-obfuscator ./vless/index.js --output ./vless/_worker.js \
+          npx javascript-obfuscator ./vless/_worker.js --output ./vless/_worker_obfuscated.js \
           --compact true \
           --control-flow-flattening true \
           --control-flow-flattening-threshold 1 \
@@ -78,7 +78,7 @@ jobs:
         run: |
           git config --local user.email "github-actions[bot]@users.noreply.github.com"
           git config --local user.name "github-actions[bot]"
-          git add ./vless/_worker.js
+          git add ./vless/_worker_obfuscated.js
           git commit -m "Obfuscate _worker.js" || echo "No changes to commit"
 
       # Step 9: Deploy the Worker with Dynamic Name
